define({
	root: {
		custom: "Custom options",
		agreement: "Agreement",
		agreement1: "strongly agree",
		agreement2: "agree",
		agreement3: "neutral",
		agreement4: "disagree",
		agreement5: "strongly disagree",
		intensity: "Intensity",
		intensity1: "entirely",
		intensity2: "quite",
		intensity3: "moderate",
		intensity4: "hardly",
		intensity5: "not at all",
		frequency: "Frequency",
		frequency1: "very frequently",
		frequency2: "frequently",
		frequency3: "occasionally",
		frequency4: "rarely",
		frequency5: "never",
		quality: "Quality",
		quality1: "very good",
		quality2: "good",
		quality3: "average",
		quality4: "poor",
		quality5: "very poor",
		importance: "Importance",
		importance1: "very important",
		importance2: "important",
		importance3: "moderately important",
		importance4: "of little importance",
		importance5: "unimportant",
		rating5: "Rating 1-5",
		grades: "Grades",
		grades1: "excellent",
		grades2: "good",
		grades3: "satisfactory",
		grades4: "sufficient",
		grades5: "deficient",
		grades6: "failure"
	},

	de: true
});
