define({
	root: {
		questions: "Questions",
		lectureQuestions: "Questions for lecture",
		preparationQuestions: "Questions for preparation",
		addQuestion: "+",
		newQuestion: "New question",
		editQuestion: "Edit question",
		mode: "Type",
		lectureMode: "Lecture",
		preparationMode: "Preparation",
		subject: "Subject",
		description: "Question",
		format: "Format",
		answerOption: "Answer option",
		correctAnswers: "Correct answers",
		allowAbstentions: "Allow abstentions",
		releaseQuestion: "Release question",
		releaseStatistics: "Release statistics",
		releaseCorrectAnswer: "Release correct answer",
		singleChoice: "Single choice",
		multipleChoice: "Multiple choice",
		yesNo: "Yes/No",
		likertScale: "(Likert) scale",
		freeText: "Free text",
		noQuestions: "No questions available",
		deleteQuestion: "Delete question",
		deleteQuestionConfirm: "Do you really want to delete this question?",
		resetQuestion: "Reset question",
		resetQuestionConfirm: "Do you really want to reset this question? All answers will be deleted.",
		loadingQuestions: "Loading questions",
		creatingQuestion: "Creating question",
		updatingQuestion: "Updating question",
		deletingQuestion: "Deleting question",
		resettingQuestion: "Resetting question",
		questionSaved: "Question saved",
		questionNotSaved: "Question could not be saved",
		questionDeleted: "Question deleted",
		questionNotDeleted: "Question could not be deleted",
		questionReset: "Question reset",
		questionNotReset: "Question could not be reset"
	},

	de: true
});
