define({
	root: {
		questions: "Questions",
		lectureQuestions: "Questions for lecture",
		preparationQuestions: "Questions for preparation",
		addQuestion: "+",
		newQuestion: "New question",
		editQuestion: "Edit question",
		mode: "Type",
		lectureMode: "Lecture",
		preparationMode: "Preparation",
		subject: "Subject",
		description: "Text",
		format: "Format",
		answerOption: "Answer option",
		correctAnswers: "Correct answers",
		allowAbstentions: "Allow abstentions",
		releaseQuestion: "Release question",
		releaseStatistics: "Release statistics",
		releaseCorrectAnswer: "Release correct answer",
		singleChoice: "Single choice",
		multipleChoice: "Multiple choice",
		yesNo: "Yes/No",
		likertScale: "(Likert) scale",
		freeText: "Free text",
		noQuestions: "No questions available",
		loadingQuestions: "Loading questions",
		creatingQuestion: "Creating question",
		updatingQuestion: "Updating question",
		questionSaved: "Question saved",
		questionNotSaved: "Question could not be saved"
	},

	de: true
});
