define({
	custom: "Eigene Antworten",
	agreement: "Zustimmung",
	agreement1: "trifft voll zu",
	agreement2: "trifft eher zu",
	agreement3: "weder noch",
	agreement4: "trifft eher nicht zu",
	agreement5: "trifft nicht zu",
	intensity: "Intensität",
	intensity1: "völlig",
	intensity2: "ziemlich",
	intensity3: "mittelmäßig",
	intensity4: "kaum",
	intensity5: "gar nicht",
	frequency: "Häufigkeit",
	frequency1: "immer",
	frequency2: "oft",
	frequency3: "gelegentlich",
	frequency4: "selten",
	frequency5: "nie",
	quality: "Qualität",
	quality1: "sehr gut",
	quality2: "gut",
	quality3: "mittelmäßig",
	quality4: "schlecht",
	quality5: "sehr schlecht",
	importance: "Wichtigkeit",
	importance1: "sehr wichtig",
	importance2: "wichtig",
	importance3: "mittelmäßig wichtig",
	importance4: "weniger wichtig",
	importance5: "unwichtig",
	rating5: "Rating 1-5",
	grades: "Schulnoten",
	grades1: "sehr gut",
	grades2: "gut",
	grades3: "befriedigend",
	grades4: "ausreichend",
	grades5: "mangelhaft",
	grades6: "ungenügend"
});
