define({
	questions: "Fragen",
	lectureQuestions: "Hörsaalfragen",
	preparationQuestions: "Vorbereitungsfragen",
	newQuestion: "Neue Frage",
	editQuestion: "Frage bearbeiten",
	mode: "Typ",
	lectureMode: "Hörsaal",
	preparationMode: "Vorbereitung",
	subject: "Thema",
	description: "Text",
	format: "Format",
	answerOption: "Antwortoption",
	correctAnswers: "Korrekte Antworten",
	allowAbstentions: "Enthaltungen erlauben",
	releaseQuestion: "Frage freischalten",
	releaseStatistics: "Statistik einsehbar",
	releaseCorrectAnswer: "Korrekte Antwort einsehbar",
	singleChoice: "Einfachauswahl",
	multipleChoice: "Mehrfachauswahl",
	yesNo: "Ja/Nein",
	likertScale: "(Likert-)Skala",
	freeText: "Freitext",
	noQuestions: "Keine Fragen verfügbar",
	deleteQuestion: "Frage löschen",
	deleteQuestionConfirm: "Möchten Sie diese Frage wirklich löschen?",
	resetQuestion: "Frage zurücksetzen",
	resetQuestionConfirm: "Möchten Sie diese Frage wirklich zurücksetzen? Alle Antworten werden gelöscht.",
	loadingQuestions: "Lade Fragen",
	creatingQuestion: "Erstelle Frage",
	updatingQuestion: "Speichere Frage",
	deletingQuestion: "Lösche Frage",
	resettingQuestion: "Setze Frage zurück",
	questionSaved: "Frage gespeichert",
	questionNotSaved: "Frage konnte nicht gespeichert werden",
	questionDeleted: "Frage gelöscht",
	questionNotDeleted: "Frage konnte nicht gelöscht werden",
	questionReset: "Frage zurückgesetzt",
	questionNotReset: "Frage konnte nicht zurückgesetzt werden"
});
