define({
	session: "Session",
	sessionKeyInfo: "Geben Sie den Session-Key an Ihr Publikum weiter",
	qrCodeInfo: "QR Code für den Direkteinstieg in eine mobile ARSnova-Session anzeigen",
	newSession: "Neue Session",
	shortName: "Kürzel",
	suspend: "Sperren",
	noSession: "Keine Session ausgewählt",
	deleteSession: "Session löschen",
	deleteSessionConfirm: "Möchten Sie diese Session wirklich löschen?",
	updatingSession: "Speichere Session",
	sessionSaved: "Session gespeichert",
	sessionNotSaved: "Session konnte nicht gespeichert werden",
	sessionDeleted: "Session gelöscht",
	sessionNotDeleted: "Session konnte nicht gelöscht werden",
	export1: "Exportieren",
	createSession: "Session erstellen",
	noSessions: "Keine Sessions",
	startWithNewSession: "Sie haben bisher noch keine Sessions angelegt. Möchsten Sie in den Bearbeitungsmodus wechseln und eine neue Session erstellen?"
});
